AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Webhook Lambda for subscription tier synchronization

Parameters:
  WebhookSecret:
    Type: String
    NoEcho: true
  WebhookProvider:
    Type: String
    Default: revenuecat
    AllowedValues:
      - revenuecat
      - stripe
  UserProfileTableName:
    Type: String
    Default: UserProfileTable

Resources:
  SubscriptionWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Handler: dist/src/subscriptionWebhook.handler
      CodeUri: ./
      MemorySize: 256
      Timeout: 15
      Environment:
        Variables:
          USER_PROFILE_TABLE_NAME: !Ref UserProfileTableName
          WEBHOOK_EVENTS_TABLE_NAME: !Ref WebhookEventsTable
          WEBHOOK_PROVIDER: !Ref WebhookProvider
          WEBHOOK_SECRET: !Ref WebhookSecret
          LOG_LEVEL: info
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${UserProfileTableName}
                - !GetAtt WebhookEventsTable.Arn
      Events:
        SubscriptionWebhookRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref WebhookHttpApi
            Method: POST
            Path: /subscription-webhook

  WebhookHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Auth:
        EnableIamAuthorizer: false
      CorsConfiguration:
        AllowMethods:
          - POST
          - OPTIONS
        AllowOrigins:
          - "*"

  WebhookEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
